name: update feed

on:
  workflow_dispatch:
  schedule: 
  - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: cache
        uses: actions/cache@v4
        with:
          key: build-${{ hashFiles('_golang/**') }}
          path: _bin

      - if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - if: steps.cache.outputs.cache-hit != 'true'
        name: build
        env:
          CGO_ENABLED: 0
        working-directory: _golang
        run: go build -o ../_bin

  update:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - path: dmkt
            handles: aikatsu-academy,himeno-mieru,mamimu-meh,wao-parin
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          key: build-${{ hashFiles('_golang/**') }}
          path: _bin    
          fail-on-cache-miss: true

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}

      - name: update feed
        env:
          FILE_PREFIX:     '${{ matrix.path }}/'
          CHANNEL_HANDLES: '${{ matrix.handles }}'
        run: _bin/yt-feed

      # git here
